name: actions
on: [push]
jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: list fliles
        run: |
          ls -a
          pwd
      - name: checkout
        uses: actions/checkout@v1 
      - name: list post
        run: |
          ls -a 
          pwd   
      - name: js action 
        id: act
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: john
      - name: greet time 
        run: echo "${{steps.act.outputs.time}}" 

     