name: matrix-push
on: [push]
jobs:
  set-node:
    strategy:
      matrix:
        node_version: [6,8,10]
    runs-on: ubuntu-latest
    steps:
      - name: first check
        run: node -v
      - name: 2nd step
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}  
        run: node -v  